theme: jekyll-theme-minimal
title: Ashish Gaude
description: Passionate Software Engineer 
<br /> <a href="https://www.linkedin.com/in/ashishgaude/">LinkedIn Profile</a> 
# logo: /profile.jpeg
# show_downloads: true
