theme: jekyll-theme-minimal
title: Ashish Gaude
description: Passionate Software Engineer
  <br><br>
#   <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
#   <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="ashishgaude" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://in.linkedin.com/in/ashishgaude?trk=profile-badge">Ashish Gaude</a></div>
  <a href="https://www.linkedin.com/in/ashishgaude/">View My LinkedIn Profile</a> 
# logo: /profile.jpeg
# show_downloads: true
