theme: jekyll-theme-minimal
title: Ashish Gaude
description: Passionate Software Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/ashishgaude/">View My LinkedIn Profile</a> 
# logo: /profile.jpeg
# show_downloads: true
